### PR TITLE
added dark mode button

### LINKED ISSUE #329: ✨[feature Request]: Add Dark Mode Toggle Button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to implement a toggle button to switch between light mode and dark mode across the application. The toggle button should be accessible, user-friendly, and persistent across sessions.

### Use Case

Customization: Users can personalize their experience, enhancing satisfaction and engagement with the project.
Accessibility: Improves the visual accessibility of the project, making it usable for a broader range of users, including those with visual impairments.
Aesthetics: Modernizes the UI and gives users a choice, improving the overall look and feel of the project.
Brand Perception: Projects that offer dark mode are often seen as more advanced and user-friendly, potentially improving the project’s reputation.

### Benefits

Offering both light and dark modes caters to a wider audience, including users who prefer the aesthetics of dark mode or find it easier to focus on darker screens.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by priyashuu**
## Related Issues

- Closes #329

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)

image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by priyashuu** [comment]
@Anjaliavv51 can you please reveiew it and merge it

**Comment by priyashuu** [comment]
@Anjaliavv51 can you please reveiew it and merge it

**Comment by priyashuu** [comment]
@Anjaliavv51 can you please reveiew it and merge it

**Comment by priyashuu** [comment]
@Anjaliavv51 can you please reveiew it and merge it

**Comment by Anjaliavv51** [comment]
@priyashuu 
place the button , as floating one the webpage down of navbar it should be fixed.

**Comment by priyashuu** [comment]
@Anjaliavv51 done with changes

**Comment by Anjaliavv51** [comment]
@priyashuu thanks for this implementation

**Pull request merged**
