### PR TITLE
[feature Request]: enhance the logo #298

### PR DESCRIPTION
**Pull request by Khushi-51**
Pull Request: Updated Logo and Navbar with Gradient Background
Description
This PR includes an update to the project’s logo along with a modern gradient background for the navigation bar, enhancing the overall aesthetic and user experience of the site.

Changes Made:
- Logo Update: Replaced the old logo with a fresh, more modern design that better reflects the project’s identity.
- Navbar Gradient Background: Introduced a sleek gradient background to the navbar, complementing the new logo and improving visual appeal.
- Maintained the functionality and structure of the navigation elements, ensuring they remain easy to use.

Screenshots:
Before: 
image

After (Logo & Navbar):  
image

Why this change?
- Logo Update: The previous logo felt outdated and didn’t align with the current direction and values of the project. The new logo is modern, recognizable, and more in line with branding standards.
- Navbar Enhancement: The gradient background complements the new logo, giving the website a more polished and professional look. This update improves first impressions and enhances the overall user interface.

Priority:
High — This update is key to the visual branding and user experience of the project.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Khushi-51 width should be decreadsed.

image

**Comment by Khushi-51** [comment]
@Anjaliavv51 of what?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 of what?

Navbar

**Comment by Khushi-51** [comment]
image
please add labels gssoc-ext and hactoberfest.

**Comment by Anjaliavv51** [comment]
> image please add labels gssoc-ext and hactoberfest.

decrese even the height of navbar make sure u implement the navbar to all hmtl pages.

**Comment by Khushi-51** [comment]
done

**Comment by Anjaliavv51** [comment]
@Khushi-51 it is not good , it wontfix , create someother issue.

**Pull request closed without merging**
