### PR TITLE
[feature Request]: Want to improve design of cart page 

### PR DESCRIPTION
**Pull request by Mr-DK07**
@Anjaliavv51  I have changes the UI of the Cart page. Just take a look. If you want any improvement, just tell me.

Before: -
Screenshot 2024-10-02 100838

After: -
Screenshot 2024-10-02 100852

If you are merging don't forget (Level) it.

#26

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Mr-DK07 please make sure colors matches the website!

**Comment by Mr-DK07** [comment]
@Anjaliavv51 It is updated

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 It is updated

i canit see any commits though?

**Comment by Anjaliavv51** [comment]
@Mr-DK07 ur changes are not updated pls check the below screenshoot.

image

**Comment by Mr-DK07** [comment]
Like which button colour, do you want to change

**Comment by Mr-DK07** [comment]
@Anjaliavv51  bottom button colour (Bill Amount, Total ) looks good on your website without change.

**Comment by Anjaliavv51** [comment]
@Mr-DK07 please change the color and also resolve conflicts.

**Comment by Mr-DK07** [comment]
@Anjaliavv51 okay

**Comment by Mr-DK07** [comment]
Screenshot 2024-10-02 192424


@Anjaliavv51  Is it good?

**Comment by Anjaliavv51** [comment]
> Screenshot 2024-10-02 192424
> 
> @Anjaliavv51 Is it good?

i appreciat eur afforts , but i am not satisfied with those colors

**Comment by Mr-DK07** [comment]
@Anjaliavv51  can you explain, what exactly do you want?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 can you explain, what exactly do you want?

make sure the colors matches the background

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 can you explain, what exactly do you want?

orelse set the color as transparent.

**Comment by Mr-DK07** [comment]
@Anjaliavv51 Check these screenshot and tell me which one do you prefer for your website.

1.
Screenshot 2024-10-02 201350

2.
Screenshot 2024-10-02 201607

3.
Screenshot 2024-10-02 202035

**Comment by Anjaliavv51** [comment]
@Mr-DK07 3

**Comment by Mr-DK07** [comment]
> @Mr-DK07 3

@Anjaliavv51 Okay I am going to commit the changes, make sure to add level also like (level 1, level 2, level 3) before merging.

**Comment by Anjaliavv51** [comment]
> > @Mr-DK07 3
> 
> @Anjaliavv51 Okay I am going to commit the changes, make sure to add level also like (level 1, level 2, level 3) before merging.

I will @Mr-DK07 don't worry.

**Comment by Mr-DK07** [comment]
@Anjaliavv51 are you going to merge it.
I have committed the changes.

**Comment by Anjaliavv51** [comment]
@Mr-DK07 

image

overlap, please check it.

**Comment by Mr-DK07** [comment]
@Anjaliavv51 Not understanding, are you talking about order now button

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 Not understanding, are you talking about order now button

Yes and also in footer

**Comment by Mr-DK07** [comment]
@Anjaliavv51  check this out.
Screenshot 2024-10-02 232615

**Comment by Anjaliavv51** [comment]
@Mr-DK07 pls join the meet
https://meet.google.com/ntw-xiho-tvg

**Comment by Anjaliavv51** [comment]
@Mr-DK07 pls join the meet
https://meet.google.com/ntw-xiho-tvg

**Comment by Mr-DK07** [comment]
@Anjaliavv51 just check it.

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 just check it.

gimme a min

**Comment by Anjaliavv51** [comment]
@Mr-DK07 keep contributing to our repo thank you!

**Pull request merged**
