### PR TITLE
Payment UI Improved #165

### PR DESCRIPTION
**Pull request by ghost**
issue no #165 
1. Implemented a new layout for payment method selection with improved visual hierarchy.

2.  Added icons for each payment method to enhance visual recognition.

3.  Implemented dynamic showing/hiding of payment details of credit card and added placeholders of the credit card ### [form](#165 )

### CODE REVIEW

**Comment by ghost** [comment]
heyy i am sorry i dont know how to link an issue . I was assigned #165 earlier this one is for that issue

**Comment by Anjaliavv51** [comment]
> heyy i am sorry i dont know how to link an issue . I was assigned #165 earlier this one is for that issue

No problem next time onwards, don't forget to mention issue number in PR description box itself

**Comment by ghost** [comment]
hey now what can i do then ??

**Comment by Anjaliavv51** [comment]
@Monu2114 Great Work , Contribute to our repo frequently, I will assign u asap.
Thank For Wonderful UI😄🚀

**Comment by ghost** [comment]
> @Monu2114 Great Work , Contribute to our repo frequently, I will assign u asap. Thank For Wonderful UI😄🚀

Thankyou so much !! That was my first pull request for hacktoberfest :))

**Pull request merged**
