### PR TITLE
Add Zoom Effect to Images with Class .menu on Hover

### PR DESCRIPTION
**Pull request by harshpareshbhaigosalya**
## Description

PR#175
Issue Description
To enhance the user experience, improve the UI of the image display on the collection page by adding a hover effect.

## Related Issues
Suggested Change
Currently, the images with the class .menu do not have any interactive effect when hovered over. To improve the user experience and visual appeal, I suggest adding a zoom effect to these images when a user hovers over them.

- Closes #

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)

Screenshot 2024-10-04 160542

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by harshpareshbhaigosalya** [comment]
Thank you! @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@harshpareshbhaigosalya full the PR description properly.

**Comment by harshpareshbhaigosalya** [comment]
Please consider this issue under the GSSoC Extended and Hacktoberfest Accepted tags.

**Comment by Anjaliavv51** [comment]
> Please consider this issue under the GSSoC Extended and Hacktoberfest Accepted tags.

Enter the issue number in PR description and place screenshot of your changes too

**Pull request merged**
