### PR TITLE
All the pages have the updated UI of the contactus page

### PR DESCRIPTION
**Pull request by trahulprabhu38**
## Related Issues

-All the pages have the updated UI of the contact US page

## Type of PR

- [x] (enhancement)

## Screenshots / videos (if applicable)
Screenshot 2024-10-02 at 3 15 22 PM

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by trahulprabhu38** [comment]
hopefully i have covered all the pages. sorry for the trouble.

**Comment by Anjaliavv51** [comment]
> hopefully i have covered all the pages. sorry for the trouble.

No issues.

**Comment by trahulprabhu38** [comment]
what is the next step now?

**Comment by Anjaliavv51** [comment]
> what is the next step now?

I need to merge the code that's it.

**Comment by trahulprabhu38** [comment]
thank you for the opportunity. and if i create a new PR on this  about a different issue 
will it be counted as a different PR?

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 yes

**Comment by Anjaliavv51** [comment]
Keep contributing to our website frequently 🚀

**Pull request merged**
