### PR TITLE
Footer adjusted with small device responsiveness in cart , about ,services ,collection section 

### PR DESCRIPTION
**Pull request by Abbas7120**
Made footer UI same in each section label it gssoc - extd level (2/3) hacktoberfest-accepted
image
image

#466 Issue made by me and resolved

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Abbas7120 resolve merge conflicts.

**Comment by Abbas7120** [comment]
Done!

**Comment by Anjaliavv51** [comment]
@Abbas7120 menu and service page code is load diff

image

**Comment by Anjaliavv51** [comment]
> Done!

it is not made responsive , make it responsive according to the dimensions , see the below image u can click on them and u can get the dimensions

image

**Comment by Abbas7120** [comment]
But my task is to made footer section same in all sections so I do it

**Comment by Abbas7120** [comment]
and it is made

**Comment by Anjaliavv51** [comment]
> and it is made

u didn't made it responsive as ur dimensions are in appropriate , ur changes r not applied.
to get perfect dimensions , u need to explore that.

**Comment by Abbas7120** [comment]
but my main task is to made all section footer same that i do

**Comment by Anjaliavv51** [comment]
> but my main task is to made all section footer same that i do

mention the related issue number in PR description.

**Comment by Abbas7120** [comment]
#466

**Comment by Anjaliavv51** [comment]
> #466

then y did u mention footer adjusted with small screens name as for the PR.

**Comment by Anjaliavv51** [comment]
> #466

no issue , overlap of footer in menu.html page

image

**Comment by Abbas7120** [comment]
Mam as on my PC in some small devices Dimension its looking good this so that why I added with this commit 
image

**Comment by Anjaliavv51** [comment]
@Abbas7120 no issue , for footer also add all these social icons.

image

**Comment by Anjaliavv51** [comment]
@Abbas7120 more over update ur branch.

**Pull request closed without merging**
