### PR TITLE
Added scroll progress bar into the website

### PR DESCRIPTION
**Pull request by Tejashri-Taral**
Hey @Anjaliavv51 ,

I have added the Scroll down progress bar in the website
closes issue #480

****Video****

https://github.com/user-attachments/assets/9311782e-c88d-4d27-9ddf-e917c61fc904

**Please take a look**

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Tejashri-Taral implement these effects to all pages.

**Comment by Tejashri-Taral** [comment]
Hey @Anjaliavv51 I have added scroll progress bar as well as scroll down bar
image

**Comment by Anjaliavv51** [comment]
@Tejashri-Taral but decerase thickness of the bar.

**Comment by Anjaliavv51** [comment]
@Tejashri-Taral progress bar UI color should match , the electronic's pagr colors

image

**Comment by Tejashri-Taral** [comment]
@Anjaliavv51 is it ok now?

**Comment by Tejashri-Taral** [comment]
@Anjaliavv51 is it ok now?

**Comment by Anjaliavv51** [comment]
@Tejashri-Taral feature is not added to menu.html page.

**Comment by Anjaliavv51** [comment]
check in below deployment image of your changes.

image

**Comment by Tejashri-Taral** [comment]
@Anjaliavv51

**Pull request closed without merging**
