### PR TITLE
home-page-redirection-#32

### PR DESCRIPTION
**Pull request by amankumarcu**
## Issue 
(#32 )

## Description
To resolve the "Cannot GET /Home.html" error, the Home button's link should be updated to direct users to index.html. This can be achieved by modifying the HTML code for the Home button. Ensure that the link is set correctly:

## Related Issues
None

## Type of PR
- [Bug] ()

## Screenshots / videos (if applicable)
<video src="https://github.com/user-attachments/assets/9ba222c2-f81e-419a-a7e7-81369a089f56">

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@amankumarcu please add related issue number in PR description.

**Comment by Anjaliavv51** [comment]
@amankumarcu I will assign u level 3 label for PR , if check redirection of all links in website.

**Comment by amankumarcu** [comment]
ok i wiil check that @Anjaliavv51

**Comment by amankumarcu** [comment]
checked all the links @Anjaliavv51 
only the home page button has issue.
<video src ="https://github.com/user-attachments/assets/56236614-b847-4033-a807-74af21bc8d94">

**Comment by amankumarcu** [comment]
Pl merge it @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@amankumarcu in all html pages.

**Comment by Anjaliavv51** [comment]
@amankumarcu I can see only one file changed.

**Comment by amankumarcu** [comment]
check now @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@amankumarcu please delete the branch and create PR

**Pull request closed without merging**
