### PR TITLE
Bookservice page completely changed

### PR DESCRIPTION
**Pull request by shivamv003**
Bookservice page completely changed
## Description
changed the book service page by adding cards and a retro background image making it look more cleaner and retro

## Related Issues
#212 

## Type of PR

- [Enhancement ] ()

## Screenshots / videos (if applicable)
image
image

## Checklist

- [x ] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [ x] I have updated my branch and synced it with project `main` branch before making this PR
- [x ] I have performed a self-review of my code
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@shivamv003 remove green color add colors related to the website

**Comment by shivamv003** [comment]
@Anjaliavv51 check this

image

**Comment by Anjaliavv51** [comment]
@shivamv003 in ur deploy contact page is fully distorted.

image

**Comment by shivamv003** [comment]
@Anjaliavv51 I am fixing it

**Pull request closed without merging**
