### PR TITLE
Add details for items 

### PR DESCRIPTION
**Pull request by TanviGandhotra**
## Description
#449 fixes
I have description for all ur collection ,
1.added read more btn
2.then create html files
3.then link it to read more btn
i guess 16 new html file are added.

## Type of PR

- [Enhancement] ()

## Screenshots / videos (if applicable)
image
image
new html files added for this
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

hope u like it.Plzz give me level also,1,2 or3 which u think i deserve for this.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@TanviGandhotra u changes made collection page card misaligned.

**Comment by TanviGandhotra** [comment]
@Anjaliavv51 what.plz wait i will correct it .u will accept na.will u send me ss plz so i get to know.

**Comment by TanviGandhotra** [comment]
@Anjaliavv51  
by my changes:
image
previus:
image
plzz see

**Comment by TanviGandhotra** [comment]
@Anjaliavv51  
image
do u want like this?

**Comment by TanviGandhotra** [comment]
i have sent u ss also .I dont know in closed pull request if u getnotified
or not .so plzz see that and let me know the change u want i will do  that.

**Pull request closed without merging**
