### PR TITLE
Added Contributor's Page 

### LINKED ISSUE #453: Adding Contributors page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

### Use Case

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by TBorundia**
## Description
Added Contributor's Page that matches with the overall theme of website.
It fetches the data directly from the repo. It is easy to navigate to the contributor's profile.

## Related Issues
- Closes  #453

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/68d6ad8f-2170-4f80-88cf-5313c617725f

## Checklist
 [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
 [X]  I have updated my branch and synced it with project `main` branch before making this PR
 [X]  I have performed a self-review of my code
 [X]  I have tested the changes thoroughly before submitting this pull request.
 [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
 [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by TBorundia** [comment]
@Anjaliavv51 , I have opened new PR with the required changes. Please review it.
Thank You!!

**Comment by Anjaliavv51** [comment]
@TBorundia add contributor link in footer section to all html pages.

**Comment by TBorundia** [comment]
@Anjaliavv51 , Done !!

**Comment by Anjaliavv51** [comment]
@TBorundia check below , u added to times don't repeat the footer tag again just add one li with a with link redirection address.

image

**Comment by Anjaliavv51** [comment]
@TBorundia both in menu.html page and also contact.html page , in contact.html page overlap is found.

image

**Comment by TBorundia** [comment]
@Anjaliavv51 , It occured due to the conflict in branch. I have resolved it. Please check it

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 , It occured due to the conflict in branch. I have resolved it. Please check it

contributor page is misaligned.

image

**Comment by TBorundia** [comment]
@Anjaliavv51 
image

**Comment by Anjaliavv51** [comment]
@TBorundia thank for these great changes awarding u with level 3 , for ur efforts!

**Comment by TBorundia** [comment]
@Anjaliavv51 Thank You so much !!

**Pull request merged**
