### PR TITLE
✨[feature Request]: Integrating Indian Retro Museums with Location Links

### PR DESCRIPTION
**Pull request by ghost**
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The retro website currently focuses on showcasing vintage collections but does not provide any information or access to retro museums across India, which are key cultural touchpoints for enthusiasts. To address this, the website needs a feature that includes a curated list of Indian retro museums along with integrated location links that allow users to navigate to these museums via Google Maps.

### Use Case

Users visiting the retro website are often enthusiasts of vintage culture and would likely be interested in exploring physical retro museums. With the new feature, users can browse through a list of retro museums, view details of each, and easily find directions to the museum using Google Maps. This allows them to transition from the online experience of viewing vintage collections to real-world interactions by visiting historical retro museums. The website will become a one-stop resource for both virtual exploration and real-life visits.

### Benefits

By integrating retro museum locations with Google Maps, the website enhances user engagement, providing a richer and more interactive experience. This feature not only helps users discover cultural landmarks but also encourages them to visit these museums, deepening their appreciation for retro history and heritage

### Add ScreenShots

Screenshot 2024-10-15 231432

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### CODE REVIEW

**Comment by snehhhcodes** [comment]
@Anjaliavv51 added the navbar as u suggested

hoping you will give it a level3 atleast!!

**Comment by Anjaliavv51** [comment]
@snehhhcodes ur changes made misaligment of the website check in below link and screenshoot

https://deploy-preview-601--rococo-mooncake-0d89f7.netlify.app/#

image

**Comment by Anjaliavv51** [comment]
closinh the PR create another PR

**Comment by snehhhcodes** [comment]
@Anjaliavv51 any update on it?

**Pull request merged**
