### PR TITLE
code duplication removed

### PR DESCRIPTION
**Pull request by amankumarcu**
## Issue 
(#147  )

## Description
code duplication in services.html removed due to which it was not able to open.

## Related Issues
None

## Type of PR
- [Bug] ()

## Screenshots / videos (if applicable)
<video src="https://github.com/user-attachments/assets/9ba222c2-f81e-419a-a7e7-81369a089f56">

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by amankumarcu** [comment]
@Anjaliavv51 merge it. the services page will start working

**Comment by Anjaliavv51** [comment]
@amankumarcu update ur branch

**Comment by amankumarcu** [comment]
This branch is up to date with Anjaliavv51/Retro:main. @Anjaliavv51

**Comment by amankumarcu** [comment]
this issue is in the updated version i have checked. @Anjaliavv51 
Screenshot 2024-10-03 at 10 49 17 PM

**Comment by amankumarcu** [comment]
merge it so that i can work on the contact us page @Anjaliavv51

**Pull request merged**
