### PR TITLE
Created contact.html  

### LINKED ISSUE #143: enhancing the contact page by making it responsive to all screen type
A responsive "Contact Us" page is essential for ensuring that users can easily reach out, regardless of the device they are using. By making it adaptable to all screen types, you guarantee that your visitors can have a seamless experience on smartphones, tablets, desktops, or any other device.

### PR DESCRIPTION
**Pull request by sejals23**
Fixes Issue no #143
Enhances the contact page and have made it responsive to all screen type...

## Related Issues

- Closes #143

## Type of PR

- [ ] ()

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by sejals23** [comment]
Screenshot 2024-10-05 133543

@Anjaliavv51 Created the contact page

**Review by Deekshit7483 — CHANGES_REQUESTED** [review]
Screenshot from 2024-10-06 16-10-43
### **The send message button is not properly aligned or functioning as expected**

Screenshot from 2024-10-06 16-13-17
### **The text is overlapping, causing display issues.**

**Comment by sejals23** [comment]
@Deekshit7483 I have already re-design the contact page

**Comment by Anjaliavv51** [comment]
@sejals23 i am closing this PR , it has no effect in the forked repo , please create some other issue i will assign u asap.

**Pull request closed without merging**
