### PR TITLE
Enhanced Contact Section: Improved Form Design, Alignment, and Navigation Integration

### PR DESCRIPTION
**Pull request by shivamv003**
Enhanced Contact Section: Improved Form Design, Alignment, and Navigation Integration
## Description
Font Update:

The font across the "Contact Us" section was changed to a more modern and clean typeface, providing a consistent and professional look.
Form Alignment:

The contact form was enclosed in a well-defined box with a thin border and rounded corners, enhancing its visual appeal.
The form now occupies 25% of the screen width on the right side of the page, creating a balanced layout that leaves space for the Google Maps integration on the left.
Spacing Adjustments:

The space between the input fields and the "Send Message" button was reduced to make the form more compact and user-friendly.
Margins and paddings were fine-tuned to ensure proper alignment and spacing throughout the form.
Google Maps Alignment:

The Google Maps iframe was aligned with the contact form, ensuring that both elements sit at the same vertical level, creating a harmonious layout for the page.
Submit Button Customization:

The "Send Message" button was redesigned with a new background color and more rounded edges. Text alignment was centered perfectly, improving the visual balance of the button.
Bottom Navigation Bar Integration:

A simplified version of the contact form was added to the bottom navigation bar, making it easy for users to reach out from any section of the website.
This form follows the same design principles, with consistent font and padding adjustments, ensuring a cohesive user experience across the site.

## Related Issues
None

- Closes #

## Type of PR

- [ Enhancement] ()

## Screenshots / videos (if applicable)
image
image

## Checklist

- [ x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x ] I have updated my branch and synced it with project `main` branch before making this PR
- [x ] I have performed a self-review of my code
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@shivamv003 box contains other color which doesn't match with website color.

**Comment by shivamv003** [comment]
Thank you for bringing this to my attention, I will look into it.

**Comment by shivamv003** [comment]
changed the color according to the website
image

**Comment by Anjaliavv51** [comment]
@shivamv003 please update ur branch and commit the changes.

**Comment by Anjaliavv51** [comment]
@shivamv003 please create a new PR anna create a new branch and procide

**Comment by shivamv003** [comment]
done

**Pull request merged**
