### PR TITLE
Add Product Filtering option

### LINKED ISSUE #447: ✨[feature Request]: Add Product Filtering option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implementing a product filtering option enhances user experience by allowing customers to quickly find items that meet their specific preferences, streamlining the shopping process, increasing engagement, and ultimately boosting conversion rates by making the search for relevant products easier and more efficient.

### Use Case

A product filtering option enhances user experience by allowing customers to quickly find items that match their preferences. It saves time, increases satisfaction, and encourages purchases by providing a streamlined, efficient shopping experience tailored to individual needs.

### Benefits

A product filtering option enhances user experience by enabling easy navigation, increasing engagement and conversion rates, fostering trust, and supporting diverse needs. It promotes sustainability by making second-hand shopping easier, provides valuable data insights, and offers a competitive advantage in the marketplace.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by avisha191**
Add Product Filtering option 

Added a Product Filtering option to create filter options for a shopping app with a price range slider (money bar) that opens upon clicking

## Related Issues
"None"

- Closes #447 

## Type of PR

- [X ] (feature Addition)

## Screenshots / videos (if applicable)
Screenshot (403)
After clicking it appears like this
Screenshot (412)

## Checklist

- [X ] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X ] I have updated my branch and synced it with project `main` branch before making this PR
- [X ] I have performed a self-review of my code
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by avisha191** [comment]
Please check my PR

**Comment by Anjaliavv51** [comment]
> Please check my PR

mention someother , rather than electronics etc..

and also on hover their is miss aligment rectify it

**Comment by avisha191** [comment]
Okay

**Comment by avisha191** [comment]
I have changed it please check

**Pull request closed without merging**
