### PR TITLE
✨[feature Request]: Signup page UI does not matches with the Login page UI

### LINKED ISSUE #548: ✨[feature Request]: Signup page UI does not matches with the Login page UI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image
image
Signup page UI does not matches with the login page UI
@Anjaliavv51 assign this to me i want to fix that

### Use Case

Similar UI makes the user feel connected with the content

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by amitroy-thedev**
## Related Issues

- Closes #548 

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)
Before :
image

After : 
image
 Same UI as Login Page
image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by amitroy-thedev** [comment]
@Anjaliavv51 I've made the changes you can review it, in the new code i have deleted login page and register page css and combined them together in a new css file

**Comment by Anjaliavv51** [comment]
@amitroy-thedev u need to make login colors(pink color UI) same as signup , implement structure of login page

**Comment by amitroy-thedev** [comment]
@Anjaliavv51 make the login, signup and google buttons pink?
like this 
image
image

**Comment by Anjaliavv51** [comment]
@amitroy-thedev yes

**Comment by amitroy-thedev** [comment]
@Anjaliavv51 Done

**Comment by amitroy-thedev** [comment]
@Anjaliavv51 I've made the changes would you review and merge it

**Comment by amitroy-thedev** [comment]
@Anjaliavv51 I've made the changes would you review and merge it

**Pull request merged**
