### PR TITLE
update-button-issue#6

### PR DESCRIPTION
**Pull request by amankumarcu**
(#6 ) update-button-issue

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
> design of the "Order Online" and "Take out Order" buttons has been updated.

add issue number here with hastag.
@amankumarcu

**Comment by amankumarcu** [comment]
done @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@amankumarcu if u change all buttons in the similar way in the website i will add level 3 label to the PR.

**Comment by amankumarcu** [comment]
okay i will do that. thanks

**Comment by amankumarcu** [comment]
done @Anjaliavv51 
<video src="https://github.com/user-attachments/assets/f912ea3c-692e-4d3f-b885-76a6daaa2bcc"></video>

**Comment by Anjaliavv51** [comment]
@amankumarcu change the button effect in other html pages too.

**Comment by amankumarcu** [comment]
okay @Anjaliavv51

**Comment by amankumarcu** [comment]
done @Anjaliavv51 
<video src = "https://github.com/user-attachments/assets/d74bce52-de89-40bc-a016-36008a466c6f"></video>

**Comment by Anjaliavv51** [comment]
@amankumarcu changes are great!

**Review by Anjaliavv51 — COMMENTED** [review]
Approved!

**Comment by amankumarcu** [comment]
Screenshot 2024-10-02 at 12 05 54 AM
can you pl add this tag label [hacktoberfest-accepted]

**Comment by Anjaliavv51** [comment]
> Screenshot 2024-10-02 at 12 05 54 AM can you pl add this tag label [hacktoberfest-accepted]

let me just check , i need to add it to hacktoberfest , gimme a min

**Comment by amankumarcu** [comment]
Yes please. Let me know whenever you're done.
Thanks

**Comment by Anjaliavv51** [comment]
@amankumarcu PLEASE CHECK NOW

**Comment by amankumarcu** [comment]
@Anjaliavv51 still showing same. pl try to include hacktoberfest-accepted tag.

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 still showing same. pl try to include hacktoberfest-accepted tag.

Now see it i had added the topic to the repo

**Comment by amankumarcu** [comment]
yeah done, thankyou so much @Anjaliavv51

**Comment by amankumarcu** [comment]
also i am raising another issue. review it also.

**Comment by Anjaliavv51** [comment]
> also i am raising another issue. review it also.

sure.

**Pull request merged**
