### PR TITLE
 Improve Navbar Alignment, Margins, and Logo Hover Effect #299

### LINKED ISSUE #299: 🐞[bug]: Improving the UI and Hover Effects for the Nav Bar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Navbar doesn't have good alignment, margin and padding, we can certainly improve on that.
Also the Retro Logo pops up suddenly when hovered over. I can fix that also.

### Expected behavior

I can Improve the above-mentioned bugs, as well as improve the UI in general such as giving a thin border to the bar makes it more accessible and aesthetic (goes well the project aesthetic).

### Add ScreenShots

image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sagarbendale2004**
## Description
This PR addresses two main issues in the navigation bar:

- Navbar Alignment and Spacing: Improved alignment, margins, and padding for better structure and spacing within the navbar, ensuring a cleaner and more visually balanced layout.

- Logo Hover Effect: Fixed the issue where the retro logo suddenly pops up when hovered. Implemented smooth transitions to make the hover effect on the logo appear seamless and visually appealing.

## Related Issues

- Closes #299 

## Changes Implemented:

- Adjusted padding and margins in the .navbar-nav and .nav-link to create consistent spacing between the navigation links.
- Enhanced the alignment of navbar elements to ensure that they are vertically centered and visually aligned.
- Applied smooth transitions to the retro logo when hovering, preventing it from appearing suddenly. This makes the hover effect more polished.
- Maintained existing hover animations for links, ensuring that the underline and color change remain smooth.

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/62312571-3dc6-4629-8f3c-234de8fc14b3

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by sagarbendale2004** [comment]
@Anjaliavv51  I fixed the navbar issue completely. Also I add hovering effect so please review my changes and merge my PR as soon as possible.

**Comment by Anjaliavv51** [comment]
@sagarbendale2004 implementation is not good , i am closing this PR.

**Comment by sagarbendale2004** [comment]
@Anjaliavv51 what actually do you want.??

**Comment by sagarbendale2004** [comment]
@Anjaliavv51  You can tell me what changes do you want. Can you describe the details as you wanted for navbar.

**Pull request closed without merging**
