### PR TITLE
✨[feature Request]: Hover on question of FAQ will display answer

### LINKED ISSUE #437: ✨[feature Request]: Hover on question of FAQ will display answer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On hover of question of FAQ the answer will be be shown with smooth transition 
similar to faq here https://style-share.vercel.app/app/

### Use Case

It makes more good looking

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by jvkousthub**
## Description
Added hover effect to faq section where upon hover the answer will be displayed

## Related Issues

- Closes #437 

## Type of PR

- [x] (Feature Addition)

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/05464318-cabb-4787-bc0a-57fd5e79fb36

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
> ## Description
> Added hover effect to faq section where upon hover the answer will be displayed
> 
> ## Related Issues
> * Closes [✨[feature Request]: Hover on question of FAQ will display answer #437](https://github.com/Anjaliavv51/Retro/issues/437)
> 
> ## Type of PR
> * [x]  (Feature Addition)
> 
> ## Screenshots / videos (if applicable)
>  Screen.Recording.2024-10-13.134333.mp4 
> ## Checklist
> * [x]  I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
> * [x]  I have updated my branch and synced it with project `main` branch before making this PR
> * [x]  I have performed a self-review of my code
> * [x]  I have tested the changes thoroughly before submitting this pull request.
> * [x]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> 
> ## Additional context:

this change is not good , coz arrows should be also displayed.

**Comment by jvkousthub** [comment]
> > ## Description
> > Added hover effect to faq section where upon hover the answer will be displayed
> > ## Related Issues
> > 
> > * Closes [✨[feature Request]: Hover on question of FAQ will display answer #437](https://github.com/Anjaliavv51/Retro/issues/437)
> > 
> > ## Type of PR
> > 
> > * [x]   (Feature Addition)
> > 
> > ## Screenshots / videos (if applicable)
> > Screen.Recording.2024-10-13.134333.mp4
> > ## Checklist
> > 
> > * [x]   I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
> > * [x]   I have updated my branch and synced it with project `main` branch before making this PR
> > * [x]   I have performed a self-review of my code
> > * [x]   I have tested the changes thoroughly before submitting this pull request.
> > * [x]   I have provided relevant issue numbers, screenshots, and videos after making the changes.
> > * [x]   I have commented my code, particularly in hard-to-understand areas.
> > 
> > ## Additional context:
> 
> this change is not good , coz arrows should be also displayed.
@Anjaliavv51 
please tell if any more changes are required ill edit the code

**Comment by jvkousthub** [comment]
https://github.com/user-attachments/assets/dd3c5c6a-a4d9-4c4d-af07-25b4c5b4275f

will it be fine??? @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@jvkousthub it should have arrow pointing down when it is closed and arrow pointing up when opened.

**Comment by jvkousthub** [comment]
> @jvkousthub it should have arrow pointing down when it is closed and arrow pointing up when opened.

ok

**Comment by jvkousthub** [comment]
https://github.com/user-attachments/assets/ee24cc24-139f-468a-b4b7-7dd48ab41c0a

@Anjaliavv51 Ok??

**Comment by Anjaliavv51** [comment]
@jvkousthub add heading also increase the width like below.

image

**Comment by jvkousthub** [comment]
https://github.com/user-attachments/assets/8edb04df-825a-4581-9976-e2eaea32b213



done @Anjaliavv51

**Comment by jvkousthub** [comment]
@Anjaliavv51 add level label

**Pull request merged**
