### PR TITLE
Enhanced Signup page

### LINKED ISSUE #154: ✨[feature Request]: Enhance Login Page UI for Improved User Experience and Responsiveness
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improved Button Design: Enhancing the buttons with a more vibrant color scheme, hover effects, and transitions will make them more visually appealing and provide better user feedback.
Dynamic Form Styling: Adding smooth transitions to form fields (like focusing on input borders and improving placeholder contrast) can help guide the user’s attention.
Responsive and Mobile-Friendly Layout: Ensuring the design is fully responsive for smaller screens to improve usability across devices.
Visual Depth with Shadows and Spacing: Introducing box shadows, text shadows, and consistent spacing to create a modern, clean look that improves the hierarchy and readability of the UI.
Engaging Background: Replacing a static background with a more appealing gradient or pattern makes the page more inviting without distracting the user.

### Use Case

As a user, I want the buttons on the login page to clearly stand out and be visually inviting to click, so I feel encouraged to complete the login/signup process.
As a user, I want to see clear focus indicators when I interact with input fields, so I can easily see where I am typing, reducing the chance of errors.
As a user, I want the login page to work well on all devices, including mobile and tablet, so I can access the page anywhere with ease.
As a developer, I want to implement a UI that enhances user interaction and feedback, ensuring users can navigate the page easily.

### Benefits

Enhanced User Engagement: The improved button design and feedback (hover effects, animations) make interactions more enjoyable, encouraging users to proceed with login or signup.
Better User Experience: Dynamic form interactions, like focus state and smooth transitions, improve the form’s usability and reduce user input errors.
Increased Mobile Usability: A fully responsive layout ensures that users on mobile devices have a seamless experience, potentially increasing conversions or registrations on smaller screens.
Modern and Professional Look: Introducing modern UI elements, like shadows and smooth transitions, makes the design look up-to-date and professional, improving user trust and brand perception.
Higher Conversion Rates: A visually engaging, responsive, and user-friendly login page encourages more users to complete the signup/login process, reducing bounce rates and increasing conversions.

### Add ScreenShots

Screenshot 2024-10-04 001038

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sunilkumarchavhan9**
## Description
Fixes #154

This PR introduces a comprehensive set of updates aimed at modernizing and improving the visual appeal of the login page. Key enhancements include:

Updated the color scheme to a modern 2024 palette with softer gradients and vibrant call-to-action buttons.
Improved button hover effects with subtle transitions, shadows, and scaling for a more interactive and responsive feel.
Enhanced form field focus states for better UX feedback.
Ensured responsiveness across multiple screen sizes, especially for mobile devices.
Updated fonts for improved readability and modern design.

## Related Issues

Closes # (Issue related to login page redesign)

## Type of PR

- [  UI/UX Enhancement] ()

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/3598f774-36d6-46fb-a65c-39f6e444b97a

## Checklist

I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro).
 I have updated my branch and synced it with the project main branch before making this PR.
 I have performed a self-review of my code.
 I have tested the changes thoroughly before submitting this pull request.
 I have provided relevant issue numbers, screenshots, and videos after making the changes.
 I have commented my code, particularly in hard-to-understand areas.

## Additional context:

These enhancements were made to bring the login page in line with modern UI trends, ensuring the interface is more user-friendly, visually appealing, and responsive to different devices.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Sunilkumarchavhan9 changes are great but ,their should be space between the boxes , IMO

**Comment by Sunilkumarchavhan9** [comment]
@Anjaliavv51  yes but this thing is unique I taken 2024 ui ux design idea  ok if ur not satisfied I will change

**Comment by Anjaliavv51** [comment]
@Sunilkumarchavhan9 ur work is good , but their are some adjustments need to be done.

**Comment by Anjaliavv51** [comment]
image

overflow of inputs

that need to rectified that's it.

**Comment by Sunilkumarchavhan9** [comment]
@Anjaliavv51 yeah I will do that

**Comment by Anjaliavv51** [comment]
@Sunilkumarchavhan9 any progress.

**Comment by Sunilkumarchavhan9** [comment]
@Anjaliavv51 sorry  for delay  bcz  I have extra classes in college so I didn't make it so I will do within some time

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 sorry for delay bcz I have extra classes in college so I didn't make it so I will do within some time

okay

**Comment by Sunilkumarchavhan9** [comment]
Screenshot 2024-10-04 220324
 changes are done can u look at it once@Anjaliavv51

**Comment by Anjaliavv51** [comment]
> Screenshot 2024-10-04 220324 changes are done can u look at it once@Anjaliavv51

Password box should be adjusted

**Pull request merged**
