### PR TITLE
✨[feature Request]: Adding icons on services page.

### LINKED ISSUE #167: ✨[feature Request]: Adding icons on services page.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On the Services page, there is a significant amount of blank space on the cards for the "Take Experience," "Book Now," and "Take Subscription" sections. 

### Use Case

Filling up blank spaces with meaningful visuals (icons).
Improving readability and overall design by aligning the contact us section.
Making the page feel more polished and professional.

### Benefits

Better User Experience (UX): Reducing empty space and improving alignment will make the page easier to navigate and visually appealing.
Clarity: Icons will quickly convey the purpose of each card to users, improving usability.

### Add ScreenShots

retroissue

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Vaishh18**
✨[feature Request]: Adding icons on services page.
## Description
This PR updates the services page by adding icons above each section, enhancing the visual appeal and user experience. The icons align with the themes of the services offered on the page (e.g., Vintage Vibe, Event Services, and Delivery Subscription).

## Related Issues
- Closes #167

## Type of PR
- [x] Feature

## Screenshots / videos (if applicable)
Screenshot (1071)

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Vaishh18** [comment]
Hello @Anjaliavv51 ,please approve the changes.

**Comment by Anjaliavv51** [comment]
@Vaishh18 changes are good , but u didn't add images in images folder so that , it is appearing like below in the preview of ur code changes, to the fork.

image

**Comment by Vaishh18** [comment]
I have added images in the Images folder, do i have to do it in a different folder ,Am i doing something wrong ,please assist @Anjaliavv51 .Thank you
Screenshot (1086)

**Comment by Vaishh18** [comment]
@Anjaliavv51 ,please merge the changes.

**Comment by Anjaliavv51** [comment]
@Vaishh18 great work , do contribute to our repo frequently!

**Pull request merged**
