### PR TITLE
Added small icons in contact us page in home page and about page

### PR DESCRIPTION
**Pull request by BVPKARTHIKEYA**
i have added icons in contact us page as shown!
WhatsApp Image 2024-10-13 at 14 22 49_ff74970e
WhatsApp Image 2024-10-13 at 14 29 02_bf6e0c43
Hope you like it!!

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@BVPKARTHIKEYA add it to all html pages in the repo in footer section.

**Comment by BVPKARTHIKEYA** [comment]
can you mention the names of html pages for collections and services i will make changes!!

**Comment by BVPKARTHIKEYA** [comment]
and i would like to redesign the contact us page in a better manner!!
would you like me to do that also!!

**Comment by Anjaliavv51** [comment]
> and i would like to redesign the contact us page in a better manner!! would you like me to do that also!!

to all html-pages.

**Comment by BVPKARTHIKEYA** [comment]
i have updated contact us icons to all html pages and i have redesigned the broken contact us page !!
WhatsApp Image 2024-10-13 at 14 22 48_6d51c616
WhatsApp Image 2024-10-13 at 14 29 01_bf3e6e49
WhatsApp Image 2024-10-13 at 15 09 47_fc315428
WhatsApp Image 2024-10-13 at 15 12 59_7d30fab3
WhatsApp Image 2024-10-13 at 15 37 25_49e4b805
WhatsApp Image 2024-10-13 at 15 41 14_5428d1dd
WhatsApp Image 2024-10-13 at 15 41 32_73fbfced
WhatsApp Image 2024-10-13 at 15 42 01_53705eeb

Hope you Like it!!
please approve my pr with best level!!

**Comment by Anjaliavv51** [comment]
@BVPKARTHIKEYA resolve merge conflicts

**Comment by BVPKARTHIKEYA** [comment]
resolved!!
thanks for your feedback

**Comment by Anjaliavv51** [comment]
@BVPKARTHIKEYA if redesign the contact us page , well then i will assign u , level 3.

image

image

**Comment by BVPKARTHIKEYA** [comment]
can you specify me the changes mam!!
i have already made the broken contact us page into a modern one!!
do you like my changes of contact page
my changes are:
1.showing map in a beautiful manner
2.input fields are modified
3.made the column wise option changes to row wise changes
4.added icons to the contact page

**Comment by Anjaliavv51** [comment]
> can you specify me the changes mam!! i have already made the broken contact us page into a modern one!! do you like my changes of contact page my changes are: 1.showing map in a beautiful manner 2.input fields are modified 3.made the column wise option changes to row wise changes 4.added icons to the contact page

place contact us message in as usual page.

**Comment by Anjaliavv51** [comment]
That's it.

**Comment by BVPKARTHIKEYA** [comment]
so shall i remove the one present here mam!!
WhatsApp Image 2024-10-13 at 15 37 25_d5adc238

**Comment by Anjaliavv51** [comment]
> so shall i remove the one present here mam!! WhatsApp Image 2024-10-13 at 15 37 25_d5adc238

Yes.u need to place it in as usual place in footer section.

**Comment by BVPKARTHIKEYA** [comment]
ok mam i will do the required changes!!
Thanks for your feedback!

**Comment by BVPKARTHIKEYA** [comment]
image
Added contact us form in the footer itself!
Hence the changes requested are done!! mam

**Comment by Anjaliavv51** [comment]
@BVPKARTHIKEYA gap between footer of social icons.

image

**Comment by BVPKARTHIKEYA** [comment]
image
 is it ok mam??

**Comment by Anjaliavv51** [comment]
image

like this with also more social icons from the latest updated branch.

**Comment by BVPKARTHIKEYA** [comment]
ok mam!!
image
i have made the changes mam

**Comment by Anjaliavv51** [comment]
> ok mam!! image i have made the changes mam

but follow has different background color.

**Comment by BVPKARTHIKEYA** [comment]
shall i change color mam!!

**Comment by Anjaliavv51** [comment]
> shall i change color mam!!

yes color same as footer.

**Comment by BVPKARTHIKEYA** [comment]
now the color is same mam 
is it ok??
image

**Comment by Anjaliavv51** [comment]
> now the color is same mam is it ok??

yes thank for these great changes 🥳

**Comment by BVPKARTHIKEYA** [comment]
your words mean a lot to me!! 
Thank you very much!!

**Comment by Anjaliavv51** [comment]
> your words mean a lot to me!! Thank you very much!!

Appreciate ur consistency work and awarding u with level 3 label.

**Comment by BVPKARTHIKEYA** [comment]
i hope you give me the best level mam!!

**Comment by Anjaliavv51** [comment]
> i hope you give me the best level mam!!

yes did.

**Comment by BVPKARTHIKEYA** [comment]
we Shall connect on Linkedin!!
https://www.linkedin.com/in/boddeda-venkata-pavan-karthikeya-1a670b255/

**Comment by Anjaliavv51** [comment]
> we Shall connect on Linkedin!! https://www.linkedin.com/in/boddeda-venkata-pavan-karthikeya-1a670b255/

yes , sent u invitation too.

**Comment by BVPKARTHIKEYA** [comment]
Messaged u @Anjaliavv51 !!

**Pull request merged**
