### PR TITLE
✨Added Chatbot (issue #319 solved)✨

### PR DESCRIPTION
**Pull request by trahulprabhu38**
## Description

the chatbot is working , @Anjaliavv51 please review this.

https://github.com/user-attachments/assets/3a413c8d-4b32-4793-87a0-5d2d8e78f26b

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 i have one more PR to make , can u review this ,Thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 i have one more PR to make , can u review this ,Thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 i have one more PR to make , can u review this ,Thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 i have one more PR to make , can u review this ,Thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 i have one more PR to make , can u review this ,Thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 i have one more PR to make , can u review this ,Thank you.

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 i have one more PR to make , can u review this ,Thank you.

**Comment by trahulprabhu38** [comment]
@Anjaliavv51 can u review this PR ,Thank you.

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 change netlify.app name to Retro

**Comment by trahulprabhu38** [comment]
sure i can do that right away!

**Pull request closed without merging**
