### PR TITLE
✨[feature Request]:Dark Mode/ Light Mode Toggle

### LINKED ISSUE #65: ✨[feature Request]: Dark Mode/ Light Mode Toggle
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a `dark mode/light mode toggle`.

### Use Case

Allow users to switch between **dark mode and light mode** to improve visual comfort and match the UI to their preferences or environmental conditions.

### Benefits

Dark mode can `reduce eye strain` and `provide better readability, especially` in low-light conditions. Light mode, on the other hand, is `better suited for bright environments, providing contrast and clarity`.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Poushmita**
## Description

This PR adds a Dark mode/Light mode toggle feature to the website, allowing users to switch between the two modes. The feature includes style adjustments for both modes to ensure consistent visual quality in both themes.

## Related Issues

- Closes #65 

## Changes Made
- Implemented Dark mode/Light mode toggle functionality using JavaScript.
- Added new CSS styles for Dark mode.
- Updated the existing Light mode styles to ensure compatibility with the toggle functionality.
- Added an icon/button for toggling modes that is visible on all pages.

### Home Page:
**Light Mode**:
Screenshot 2024-10-05 163543
Screenshot 2024-10-05 165017

**Dark Mode**:
Screenshot 2024-10-05 163657
Screenshot 2024-10-05 164019

### About Page:
**Light Mode**:
Screenshot 2024-10-05 164131
Screenshot 2024-10-05 164833

**Dark Mode**:
Screenshot 2024-10-05 164219
Screenshot 2024-10-05 164345

### Services Page:
**Light Mode**:
Screenshot 2024-10-05 164432
Screenshot 2024-10-05 164728

**Dark Mode**:
Screenshot 2024-10-05 164509
Screenshot 2024-10-05 164600
Screenshot 2024-10-05 164646

### Contact Page:
**Light Mode**:
Screenshot 2024-10-05 165109
Screenshot 2024-10-05 165137

**Dark Mode**:
Screenshot 2024-10-05 165215
Screenshot 2024-10-05 165821

### Cart Page:
**Light Mode**:
Screenshot 2024-10-05 165926
Screenshot 2024-10-05 165954

**Dark Mode**:
Screenshot 2024-10-05 170434
Screenshot 2024-10-05 170505

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Poushmita** [comment]
@Anjaliavv51  Please check out my PR and let me know if any changes are needed.

**Comment by Anjaliavv51** [comment]
Look at the below pic , navbar is not updated.

image

**Comment by Anjaliavv51** [comment]
@Poushmita update the branch and also resolve the conflicts.

**Comment by Poushmita** [comment]
@Anjaliavv51  Changed the code for navbar and resolved the conflict. `Please let me know if anything is needed.`

## Updated 
image

**Comment by Anjaliavv51** [comment]
@Poushmita resolve conflicts and also place the dark mode button  , where i have marked in the below image it should float in the webpage.

WhatsApp Image 2024-10-08 at 15 34 13_dd8c9e8e

**Comment by Anjaliavv51** [comment]
@Poushmita this pr has to be made so many changes , and their are overlap with ur code , so i am closing the PR , and try to create another PR with perfect changes , u can ur changes in link below deploy link.

https://deploy-preview-229--rococo-mooncake-0d89f7.netlify.app/html-files/services

**Comment by Poushmita** [comment]
@Anjaliavv51  I think this conflict is occurring again and again due to the same branch. Please give me sometime, I am implementing the changes in a new branch and opening a PR request.

**Pull request closed without merging**
