### PR TITLE
aligning this to the center and adding images

### PR DESCRIPTION
**Pull request by tanushachoudhary**
## Description

issue #151 
I added two new images for online delivery and click and collect cards and aligned the heading as well as the cards to the center.

## Related Issues
this makes it look more catchier and nicer

- Closes #

## Type of PR

- [ ] (feature request)

## Screenshots / videos (if applicable)

image
image

## Checklist

- [ X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [ X] I have updated my branch and synced it with project `main` branch before making this PR
- [ X] I have performed a self-review of my code
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@tanushac pictures are not great.

**Comment by tanushac** [comment]
Ok, what is it about the pictures that you don't like? I tried to generate them using AI but the results were not good.

**Comment by tanushachoudhary** [comment]
image
Screenshot 2024-10-05 164341
@Anjaliavv51  how about these images?

**Comment by Anjaliavv51** [comment]
> image Screenshot 2024-10-05 164341 @Anjaliavv51 how about these images?

No they are not looking good.

**Pull request closed without merging**
