### PR TITLE
Enhance Footer Social Icons with Hover Effects

### PR DESCRIPTION
**Pull request by Shekhar-Raj**
## Description
Details:
I have modified the social icons in the footer.

Expected Behavior:
When a user hovers over the social icons:

The Facebook icon changes to blue.
The Instagram icon changes to pink.
All icons increase in size slightly.

<h2>Before:</h2>

https://github.com/user-attachments/assets/4c5ba593-bbed-4fd5-8712-64c8ec7efbab

<h2>After:</h2>

https://github.com/user-attachments/assets/5e984c82-1d0d-4e2b-a2b2-7f80d8808b94

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj please modify for all html pages then i will assign level 2

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj please modify for all html pages then i will assign level 2

ok ! doing for all the html pages

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj please also mention issue number with hastag in PR description

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj please also mention issue number with hastag in PR description

ya sure will do!

**Comment by Shekhar-Raj** [comment]
<h2><b>i have done [Enhance Footer Social Icons with Hover Effects](https://github.com/Anjaliavv51/Retro/pull/92#top)
#92 :<b></h2>


<h2>Changes have been made to the various pages where the social icon was at the footer, in cart.html, electronic.html and other pages.
</h2>
<h1>cart.html</h1>
<h3>Before:</h3>

image

<h1>After </h1>



https://github.com/user-attachments/assets/e1162cbe-f997-401e-a1b4-4ba14842f0ea

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj great work.

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj great work.

Thank you!

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj keep contributing to our repo!

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj keep contributing to our repo!

ya sure!

**Pull request merged**
