### PR TITLE
color

### PR DESCRIPTION
**Pull request by amankumarcu**
## Issue
(#110 )
## Description
changed the colours wherever required:-
1. home page hero section (converted to white)
2. footer social media icons (white -> brown) 

## Related Issues

- Closes #

## Type of PR

- [feature] ()

## Screenshots / videos (if applicable)
1. Screenshot 2024-10-03 at 1 46 02 AM
2. Screenshot 2024-10-03 at 1 45 38 AM

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by amankumarcu** [comment]
merge this @Anjaliavv51

**Comment by amankumarcu** [comment]
pl give it atleast a lvl2. you can give lvl3 if you wish[😊](https://emojipedia.org/smiling-face-with-smiling-eyes)

**Comment by Anjaliavv51** [comment]
@amankumarcu please create another PR coz deployment is failed m

**Comment by Anjaliavv51** [comment]
> @amankumarcu please create another PR coz deployment is failed m

@amankumarcu

**Comment by amankumarcu** [comment]
ok @Anjaliavv51

**Pull request closed without merging**
