### PR TITLE
Fix:Move to top hover is not visible on hover.

### LINKED ISSUE #455: 🐞[bug]: Move to top hover is not visible on hover.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Move to up button is not visible upon hover. and also at the bottom due to white color is not visible 

### Expected behavior

Color combination should be change of Move to top button.

### Add ScreenShots

https://github.com/user-attachments/assets/59ab39b1-cc70-4441-adc7-01aa937c3b6c
image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by gyanshankar1708**
## Description

Hover on move to top button was not visible and at the bottom the button was not visible due to white color.
I had changed the color of Move to top button on both normal and on hover.

## Related Issues

- Closes #455 

## Type of PR

- [X] (#455)

## Screenshots / videos (if applicable)

image
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

@Anjaliavv51 please review it and merge it.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@gyanshankar1708 implement the effect to all hmtl pages and also UI of the button color should match webpage color's

**Comment by gyanshankar1708** [comment]
@Anjaliavv51  I had changed to all the pages. 
Please review it nad merge it.

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 I had changed to all the pages. Please review it nad merge it.

color is not changes still. 

look in ur deployment in below link

https://deploy-preview-458--rococo-mooncake-0d89f7.netlify.app/

**Comment by gyanshankar1708** [comment]
@Anjaliavv51  I am closing this PR. I had solved #468. after merging that I'll work on this.

**Pull request closed without merging**
