### PR TITLE
Fixed text boxes gap & Header issue ! #432

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #432 

All Issue Fixed - 

Text boxes issue -
Screenshot 2024-10-13 202210
Screenshot 2024-10-13 202224

Header Issue -
Screenshot 2024-10-13 203307
Screenshot 2024-10-13 203324
Screenshot 2024-10-13 204019

## Type of PR

- [ ] ()
## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 PA kindly add level 2
because I fixed all these two main issue properly & also I don't got any level for this(#378) merge.

**Comment by Anjaliavv51** [comment]
@Subhajit-2023-44 create some other issue , these changes are not required sorry for the inconvience.

**Comment by Subhajit-2023-44** [comment]
But @Anjaliavv51 ma'am you assigned me for this issue.. 

Screenshot 2024-10-13 210102

I Fixed these issue - #432
When the cursor is moved to the "Retro Vibe is Good Vibe" text box, the text box merges with the "SIGN UP" text box. which doesn't look very good.
& the position of the Header is fixed across the page, causing it to blend in with other text, It preventing the website from looking better.

**Comment by Anjaliavv51** [comment]
> But @Anjaliavv51 ma'am you assigned me for this issue..
> 
> Screenshot 2024-10-13 210102
> 
> I Fixed these issue - #432 When the cursor is moved to the "Retro Vibe is Good Vibe" text box, the text box merges with the "SIGN UP" text box. which doesn't look very good. & the position of the Header is fixed across the page, causing it to blend in with other text, It preventing the website from looking better.

yes but now it is not required , so please mention ur issue properly

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 ma,am I mention my issue properly & also attached issue video & ss #432.. & you assigned me for this issue but now you said ...

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 ma,am I mention my issue properly & also attached issue video & ss #432.. & you assigned me for this issue but now you said ...

Sorry it's my mistake I didn't get u properly.

**Pull request closed without merging**
