### PR TITLE
📝[documentation Update]: upload a video of the website

### PR DESCRIPTION
**Pull request by Amulya-B28**
## Description
Added a video demo of the website.

## Type of PR

- [X] (Documentation)

## Screenshots / videos (if applicable)
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Amulya-B28** [comment]
@Anjaliavv51 could you please add the level tag. Thank you.

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 could you please add the level tag. Thank you.

i will add to the PR.

**Comment by Amulya-B28** [comment]
@Anjaliavv51 Mam you havent added the level tag yet..Can you please add it.

**Comment by Amulya-B28** [comment]
@Anjaliavv51 Could you please add the level tag....since it is not showing on the leaderboard...Thank you.

**Comment by Amulya-B28** [comment]
@Anjaliavv51 could you add the level tag pleasee.....

**Comment by Anjaliavv51** [comment]
@Amulya-B28 for just code change of 5 lines level won't be assigned

**Comment by Amulya-B28** [comment]
@Anjaliavv51 I understand mam but you could at least assign a level1 tag. Hoping for a positive response.

**Pull request merged**
