### PR TITLE
Enhanced the UI of the Navbar

### LINKED ISSUE #187: ✨[feature Request]: ENHANCING THE UI OF HEADER PORTION IN THE ONLINE DELIVERY SECTION
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would love to enhance the appearance of the header section by incorporating CSS to style the navigation bar, adding a visually appealing and polished look. My goal is to modify and refine the design, making it more attractive and user-friendly while maintaining functionality.

### Use Case

This feature would significantly improve the overall user experience of the project by making the navigation bar more visually appealing, organized, and intuitive to use. A well-designed header section can enhance usability by providing easy access to different sections of the website, ensuring smooth navigation. Additionally, it will contribute to a more professional and cohesive look, creating a positive first impression for users, which is essential for engaging and retaining them.

### Benefits

This feature would bring multiple benefits to both the project and the community. For the project, a well-designed and visually appealing navigation bar would improve the user interface, making it easier for users to explore the website and access key information. It also enhances the professional appeal of the platform, which could attract more users and increase overall engagement.

For the community, this enhancement promotes a smoother browsing experience, reducing frustration and encouraging repeat visits. A clean, accessible design empowers users of all technical levels to interact with the platform more efficiently, fostering a sense of inclusivity. Ultimately, it helps build a user-friendly and inviting online environment that serves the community's needs more effectively.

### Add ScreenShots

Screenshot 2024-10-04 195105

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by likitha-kapu**
[feature Request]: ENHANCING THE UI OF HEADER PORTION IN THE ONLINE DELIVERY SECTION 

## Description
I would love to enhance the appearance of the header section by incorporating CSS to style the navigation bar, adding a visually appealing and polished look. My goal is to modify and refine the design, making it more attractive and user-friendly while maintaining functionality.

## Related Issues

- Closes #187 

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)
Screenshot 2024-10-04 204451

## Checklist

- [ x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [ x] I have updated my branch and synced it with project `main` branch before making this PR
- [x ] I have performed a self-review of my code
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

Initially the nav bar didnot have any much UI but I have changed the style of the navbar and when the mouse hovers over it the colour changes to blue.

### CODE REVIEW

**Comment by likitha-kapu** [comment]
@Anjaliavv51 Just check out my pullrequest !

**Comment by Anjaliavv51** [comment]
Background color should be change according to webpage color.

**Comment by likitha-kapu** [comment]
@Anjaliavv51 
Screenshot 2024-10-04 211302
Kindly checkout this!

**Comment by likitha-kapu** [comment]
@Anjaliavv51 Kindly Checkout the screenshot! I have also aligned the text items(like Entertainment,Gadgets etc) to the center of the page .....so that it makes the page look more good!

**Comment by likitha-kapu** [comment]
@Anjaliavv51 checkout the changes I have made.....let me know if the background colour is okay?

**Comment by likitha-kapu** [comment]
@Anjaliavv51 what should I do next?Like I am contributing to opensource for the first time

**Comment by likitha-kapu** [comment]
@Anjaliavv51 thank you for accepting my pullrequest

**Pull request merged**
