### PR TITLE
Create content_based_filtering.py

### LINKED ISSUE #123: 🐞[bug]: the header and then the body text is not visible in the page ! and then the text which is placed under the welcome tag is not visible too , i can change that issues , and i can add a superb feature for that
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I hope you're doing well. I’ve noticed that there’s a visibility issue on the page:

The header and body text are not visible.
The text under the welcome tag is also hidden.
I’d like to help resolve this bug by making these elements clearly visible. Additionally, I have an idea to enhance the page with a superb feature that will improve the overall user experience.

Could you please assign this task to me? I’m excited to contribute and make meaningful changes to the project.

Looking forward to your approval!
Screenshot 2024-10-03 120602

### Expected behavior

Expected Behavior:

I expected the header, body text, and the text under the welcome tag to be clearly visible on the page, regardless of the theme or mode (e.g., light mode, dark mode). The text should be easy to read with proper contrast against the background, ensuring a seamless user experience.

### Add ScreenShots

Screenshot 2024-10-03 120602

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sv410**
Description
<!–Please include a brief description of the changes–> Added data collection and recommendation model features. The data collection tracks user interactions (clicks, views, purchases) and stores them in a database. The recommendation model uses collaborative filtering and content-based filtering to provide personalized recommendations.

Related Issues
<!–Cite any related issue(s) this pull request addresses. If none, simply state “None”–>

Closes #123 (Replace with the actual issue number if applicable)
Type of PR

[ ] Feature
Screenshots / videos (if applicable)
<!–Attach any relevant screenshots or videos demonstrating the changes–> N/A

Checklist

[X] I have gone through the contributing guide
[X] I have updated my branch and synced it with project main branch before making this PR
[X] I have performed a self-review of my code
[X] I have tested the changes thoroughly before submitting this pull request.
[X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
[X] I have commented my code, particularly in hard-to-understand areas.
Additional context:
<!–Include any additional information or context that might be helpful for reviewers.–> This feature enhances user experience by providing personalized recommendations and insights into user behavior, which can inform marketing strategies and inventory management.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@sv410 what does ur code , makes changes for the website.

**Comment by sv410** [comment]
@Anjaliavv51 This update enhances the site by adding data collection features and a recommendation model. It tracks user interactions (clicks, views, purchases) and stores them in a database. Using collaborative and content-based filtering, it provides personalized recommendations to users, improving their overall experience and offering valuable insights into user behavior. This can inform marketing strategies and inventory management.

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 This update enhances the site by adding data collection features and a recommendation model. It tracks user interactions (clicks, views, purchases) and stores them in a database. Using collaborative and content-based filtering, it provides personalized recommendations to users, improving their overall experience and offering valuable insights into user behavior. This can inform marketing strategies and inventory management.

Thank You for this feature.

**Comment by sv410** [comment]
@Anjaliavv51 pls level if u liked it to level 3! thanks a lot!

**Pull request merged**
