### PR TITLE
Add hover effect to footer section links

### LINKED ISSUE #126: ✨[feature Request]: Add hover effect to footer section links
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Original
Before changing when the user hovers it does not show any special distinction

Screenshot 2024-10-03 125834
### Suggested Change
When the user hovers on a link, change its colour.

### Use Case

User interactive and visually appealing

### Benefits

I would change the colour according to the website's theme. This would make the website interactive as the user would know when they are hovering on a particular link and also prevent them from accidentally clicking on the wrong option.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by tulikaa25**
## Description

Added underline when the user hovers on a particular link in footer section

## Related Issues

- Closes #126 

## Type of PR

- [X] (feature Request)

## Screenshots / videos (if applicable)
Screenshot 2024-10-04 205408

## Checklist

- [ X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [ X] I have updated my branch and synced it with project `main` branch before making this PR
- [ X] I have performed a self-review of my code
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Added the necessary code at the end of style.css file

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@tulikaa25 instead make a hover effect such that they form a underline under the links

**Comment by tulikaa25** [comment]
I have made the necessary changes @Anjaliavv51

**Comment by tulikaa25** [comment]
@Anjaliavv51 please review my work and close the pull request.

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 please review my work and close the pull request.

resolve merge conflicts.

**Comment by tulikaa25** [comment]
I have resolved the conflict. If it is still not resolved please do guide me @Anjaliavv51

**Comment by tulikaa25** [comment]
@Anjaliavv51 is there any more work to be done on this issue then pls guide me or else close the pull request.

**Comment by tulikaa25** [comment]
@Anjaliavv51 Ma'am please respond

**Pull request closed without merging**
