### PR TITLE
added transition effects in faq section

### LINKED ISSUE #710: ✨[feature Request]: Add hover effects to FAQ section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhance the user experience by adding smooth animations to the FAQ section. The animations should improve the interactivity and visual appeal when a user expands or collapses a question.

### Use Case

Apply a smooth sliding animation when expanding and collapsing the FAQ items.
The transition should be fast enough to keep the interaction responsive but slow enough for a smooth effect (e.g., 0.3s - 0.5s duration).
Icon Animation:
Rotate or change the icon next to each question when expanded and revert back when collapsed.
The icon animation should synchronize with the expand/collapse animation.

### Benefits

_No response_

### Add ScreenShots

https://github.com/user-attachments/assets/db229dc9-f6bc-4795-9d77-52e74aecf957

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sezallagwal**
## Description

added smooth animations to the FAQ section

https://github.com/user-attachments/assets/f3094b7e-b149-4e30-98a3-d7737f91aa97

## Related Issues

- Closes #710 

## Type of PR

- [ ] ()

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by sezallagwal** [comment]
@Anjaliavv51 Can you please review it

**Comment by sezallagwal** [comment]
@Anjaliavv51 any updates? can you assign it and give labels to  @amitb0ra

**Comment by sezallagwal** [comment]
@sanjay-kv @Anjaliavv51 any updates?

**Comment by sanjay-kv** [comment]
There is already repo provided to you via newsletter to add your unmerged PRs

**Comment by sezallagwal** [comment]
> There is already repo provided to you via newsletter to add your unmerged PRs

where? i didn't received anything.

**Pull request closed without merging**
