### PR TITLE
added animations

### PR DESCRIPTION
**Pull request by Vijitverm1234**
## Description

I've added AOS that is Animations on scroll as contribution to this website 

## Related Issues

- Closes #

Now the website is no longer static 

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)

scroll animations

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Vijitverm1234** [comment]
@Anjaliavv51 I've just completed with the first issue please check .

**Comment by Anjaliavv51** [comment]
@Vijitverm1234 please resolve conflicts.

**Comment by Vijitverm1234** [comment]
please check @Anjaliavv51  just resolved the conflict

**Comment by Anjaliavv51** [comment]
@Vijitverm1234 thank for this feature.

**Pull request merged**
