### PR TITLE
Updates Needed for About Us and Cart Pages #183

### PR DESCRIPTION
**Pull request by Kavish-Paraswar**
Subject: Issue #183 Resolved

Hello PA,
The following issues have been resolved:

The shape of the email input tag now matches the design of the message input box on the Services and Collections pages.
Additional social media tags (YouTube, Snapchat) have been added with the same features as the existing ones.
image

The duplicated navbar issue has been fixed.
The font size of the items in the cart has been adjusted.
image

All changes have been implemented successfully.

Best regards,
Kavish Paraswar

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar add those social icons to remaining webpages too then I will assign u level 2

**Comment by Kavish-Paraswar** [comment]
ok , do u want me to give a new PR request for this changes? 
and did u have a chnace to see my previous PR about the about us and cart pages #226 PR?

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar update ur branch and make the changes accordingly.

**Comment by Kavish-Paraswar** [comment]
So u want me to add social media icons to all the webpages and add those changes to this PR or Branch?

**Comment by Anjaliavv51** [comment]
> So u want me to add social media icons to all the webpages and add those changes to this PR or Branch?

yes

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar resolve the conflicts too.

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar resolve the conflicts too.

**Comment by Kavish-Paraswar** [comment]
image
NO conflicts with the base branch 
I will be adding the pr for Social media icon to this branch , so please assign level 2 atleast , then i willsend a add the icons to this branch .

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar resolve the merge conflicts.

**Comment by Kavish-Paraswar** [comment]
image
@Anjaliavv51  No conflicts with base branch for #183

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar what r the changes u made.

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar 

image

**Comment by Kavish-Paraswar** [comment]
@Anjaliavv51  i have given u proof of the changes made at the starting of the issue , please review this carefully!! 
the alignement of the cart page was not good , so i made the changes to it  and text size of the  item in cart was increased to make it more appealing to UI . 
also the email input tag length was increased , but please review these changes

**Comment by Kavish-Paraswar** [comment]
maybe in the social medai icons PR , all the changes must have been done , so its showing no changes here 
#343

**Comment by Anjaliavv51** [comment]
@Kavish-Paraswar then I will assign level 3 to #343 is it okay?

**Comment by Kavish-Paraswar** [comment]
Yess , IT IS OK maam .

**Pull request closed without merging**
