### PR TITLE
Update contact.html

### LINKED ISSUE #259: 🐞[bug]: The contact us page is messed up
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

# hey @Anjaliavv51 ,
i was looking at your website and i must say i love the ui of the website and its concept too .
# i noticed that there is some issue with the contact us page (primarily css based issues )
i would love to look into it and resolve it .
i have attached the screenshot of the issue i noticed 
please assign this issue to me with the labels 'gssoc extd' and 'hactoberfest'.
looking forward to collaborate.

### Expected behavior

a uniform and more sought out contact us page without the existing document issues

### Add ScreenShots

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sadafhukkeri**
## Related Issues

- Closes #259 #256 

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)

Before making changes -
Screenshot (154)
Screenshot (155)
Screenshot (156)
After making changes -
Screenshot (160)
Screenshot (161)

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@sadafhukkeri footer is not aligned properly.

**Comment by sadafhukkeri** [comment]
ok i will change it

**Comment by Anjaliavv51** [comment]
@sadafhukkeri resolve conflicts

**Comment by Anjaliavv51** [comment]
@sadafhukkeri it isresolved.

**Pull request closed without merging**
