### PR TITLE
make Responsiveness

### LINKED ISSUE #9: Responsive
Screenshot 2024-10-01 190256
can do responsive design.

### PR DESCRIPTION
**Pull request by ruchikakengal**
## Related Issues

- Closes #9 

## Type of PR

- [X] (feature)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

#9 Responsive

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@ruchikakengal resolve conflicts and please fill the PR template correctly and mention the issue number too.

**Comment by ruchikakengal** [comment]
@Anjaliavv51  i am not understanding what u are saying

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 i am not understanding what u are saying

u r contributing for the first time?

**Comment by ruchikakengal** [comment]
yes

**Comment by Anjaliavv51** [comment]
> yes

Okay , one min.

**Comment by Anjaliavv51** [comment]
https://meet.google.com/urf-bood-ocv

join this link , i will say u.

@ruchikakengal

**Pull request closed without merging**
