### PR TITLE
 ✨[feature Request]: Changing Navbar #186 

### LINKED ISSUE #186: ✨[feature Request]: Changing Navbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Need to improve navbar UI

### Benefits

First Come First serve who will ping first will be assigned first and awrded level 3 , they need make UI navbar Great and also , navbar should be implemented to all html pages in repo.

### Add ScreenShots

Before :

image

After :

Their should be a floating navbar , with curved edges and on hover over the link's , underlining should be displayed with glowing effect.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Mayukh-Mandal2005**
## Description
Updated the Navbar UI as asked in the issue column 
Added rounded corners with white background, underline and glowing effect on the tabs in navbar of each page with adding 1-2 more features such as cart image with count option on each page

## Related Issues

- Closes #186 

## Type of PR

- [✔️ ] (Feature update, Code Refactor)

## Screenshots / videos (if applicable)

Image of website before the Navbar UI -
image

Images of website after the updated Navbar UI-
image
image

## Checklist

- [✔️ ] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [✔️ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ✔️] I have performed a self-review of my code
- [ ✔️] I have tested the changes thoroughly before submitting this pull request.
- [ ✔️] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ✔️] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Mayukh-Mandal2005** [comment]
Hey @Anjaliavv51 
Kindly check and merge the PR please.

**Comment by Anjaliavv51** [comment]
In our collection their are some correction need to be changed.

**Comment by Mayukh-Mandal2005** [comment]
What needs to be changed?
Kindly specify the issue @Anjaliavv51 mam

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 
Kindly tell issues so I can make the necessary rectifications ASAP

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 
Kindly tell what changes need to be made so I can complete the tasks please.

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 no need it's fine , did u implement it to all html pages.

**Comment by Mayukh-Mandal2005** [comment]
Yes @Anjaliavv51 Mam
I have implemented to all HTML Pages as told by you Home, About, Services, Collection, Contact Us
I did not include on payment, sign up and login in pages as ordered by you

**Comment by Anjaliavv51** [comment]
And also one last implement it to it to electronics.html page too ,located inside htmlfiles folder please check

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 
So should I close this pull request and make a new one?

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 I am saying to implement navbar even to that page.

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 their is overflow in about , collection , 

image

image

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 only index.html page navbar is properly aligned , for remaining all , it has an overflow , please check and also implement navbar for electronics page to , check below ss

image

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 
No actually that's the design which is being implemented by bootstrap and I guess home page looks and other pages looks are similar 
And tbh the overflow condition gives a great look for the pages as when you click the Retro logo it takes you to the home page

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 it's not looking good try to adjust and also in some pages collections or about or service link is not provided.

**Comment by Mayukh-Mandal2005** [comment]
I tried to improve that condition though in every possible way but could not do the same
There is bootstrap style being getting overriden with the css files 
I hope you understand @Anjaliavv51 Mam

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 
Yeah I did not provide the links in those pages which are same as that page
For example - If you are on services page, then we do not need a services tab for that as we are on that page only
I hope that helps

**Comment by Anjaliavv51** [comment]
> I tried to improve that condition though in every possible way but could not do the same There is bootstrap style being getting overriden with the css files I hope you understand @Anjaliavv51 Mam

okay , then i will merge.

**Comment by Mayukh-Mandal2005** [comment]
If you want me to include all the tabs on all the pages i will do the same right now 
No issues @Anjaliavv51 Mam

**Comment by Anjaliavv51** [comment]
> If you want me to include all the tabs on all the pages i will do the same right now No issues


include all but avoid signup and login and cart image to other pages , except index.html page.

**Comment by Mayukh-Mandal2005** [comment]
Alright @Anjaliavv51 Mam
I will do that right away

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 why retro word is not aligned properly? in service , contact ,menu ,about.

image

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 
Mam as I mentioned before this is due to the css styles being getting overriden with the bootstrap styles
I tried to sync it with other elements in all ways but it did not work like the way we wanted

**Comment by Mayukh-Mandal2005** [comment]
I am checking it although once again if I can adjust and will update you about the same

**Comment by Anjaliavv51** [comment]
> I am checking it although once again if I can adjust and will update you about the same

okay , is everthing done now , i will merge it.

**Review by Anjaliavv51 — APPROVED** [review]
Approved!

**Comment by Anjaliavv51** [comment]
@Mayukh-Mandal2005 mention the issue number inside pr description.

**Comment by Mayukh-Mandal2005** [comment]
Hey @Anjaliavv51 
I found the problem and fixed it but I am not able to merge the commits in the PR now :(

**Comment by Anjaliavv51** [comment]
> Hey @Anjaliavv51 I found the problem and fixed it but I am not able to merge the commits in the PR now :(

Create another PR on same issue.

**Comment by Mayukh-Mandal2005** [comment]
@Anjaliavv51 Mam
Created
Please check

**Comment by Anjaliavv51** [comment]
Yes I assigned it to you

**Pull request merged**
