### PR TITLE
Fixed text orientation issue in Login page ! #378

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
## Description

Hello PR,
Fixed issue number - #378

Screenshot 2024-10-09 172512

## Related Issues

- Closes #

## Type of PR

- [ ] ()

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Subhajit-2023-44 i am not giving any level label coz , ur code changes are only a value.

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 Please give me Level, I am beginner, its just my 3rd pull request..

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 Ma'am you assigned me and said "go ahead.i will add Level label to the PR" 

Screenshot 2024-10-10 013149

Ma'am please add level 1.

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 ???

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 Ma'am you assigned me and said "go ahead.i will add Level label to the PR"
> 
> Screenshot 2024-10-10 013149
> 
> Ma'am please add level 1.

but ur code changes are not even minimal they are just change of one line.
There are some instructions given to us to award level label according to the issue and also , no of lines code had changes.

**Comment by Subhajit-2023-44** [comment]
Okay ma'am,
@Anjaliavv51 ma'am can you please tell me what should I do to get level 3 and level 2?  instructions..

**Comment by Anjaliavv51** [comment]
> Okay ma'am, @Anjaliavv51 ma'am can you please tell me what should I do to get level 3 and level 2? instructions..

ur feature should be good , if it is bug u need to verctify alot then u will be awarded level 3 or level 2.

u had implemented well and u r contributing first time as a complement i will awarded a bonus level

**Pull request merged**
