### PR TITLE
retro theme navbar added

### LINKED ISSUE #445: ✨[feature Request]:  whole template Change
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I feel the theme of  retro doesn't go with the template we are using here, I suggest We should collaborate and try something like this 
Retro   Old Computer Aesthetics
. I will try to Make some of the changes please assign  this to me. 

### Use Case

This will give the real retro vibe to the website and it might stand out

### Benefits

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by kekubhai**
## Related Issues

- Closes #445 

## Type of PR

- [#445  ] ()

## Screenshots / videos (if applicable)

image

## Checklist

- [X ] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [ X] I have updated my branch and synced it with project `main` branch before making this PR
- [ X] I have performed a self-review of my code
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@kekubhai overflow of navbar.

image

**Comment by kekubhai** [comment]
yes I guess I have made a mistake there, Check if this one is fine or not 
image

**Comment by Anjaliavv51** [comment]
> yes I guess I have made a mistake there, Check if this one is fine or not image

fine but it is not match with UI of html body

**Comment by kekubhai** [comment]
> > yes I guess I have made a mistake there, Check if this one is fine or not image
> 
> fine but it is not match with UI of html body

You can ask for create an issue for that and make someone work, people will love to work on that after you merge this one, Or I will just have to discard this as an Issue. Thanks

**Comment by Anjaliavv51** [comment]
> > > yes I guess I have made a mistake there, Check if this one is fine or not image
> > 
> > 
> > fine but it is not match with UI of html body
> 
> You can ask for create an issue for that and make someone work, people will love to work on that after you merge this one, Or I will just have to discard this as an Issue. Thanks

discard this issue , and carry to raise someother issue , coz if it is implemented it takes not only time , but also irritates aa lot with merge conflicts and bug's , so i am closing this PR and issue Sorry

**Pull request closed without merging**
