### PR TITLE
Created a login page

### LINKED ISSUE #83: Add Login page for tracking the order
The login page for this website serves as a secure gateway for users to access their personal accounts. It provides registered customers with a seamless entry point to manage their profiles, view past orders, and proceed with purchases more efficiently. For new users, the login page often includes a registration option, allowing them to create an account with ease.

### PR DESCRIPTION
**Pull request by sejals23**
## Related Issues

- Closes #83

## Type of PR

- [ ] ()

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by sejals23** [comment]
@Anjaliavv51 Login page file successfully added

**Comment by sejals23** [comment]
@Anjaliavv51 Could you now please add level 3 tag..

**Comment by Anjaliavv51** [comment]
@sejals23 send me the screenshot of ur login page changes.

**Comment by sejals23** [comment]
This is the Login page that I have made....If want me to do any change please let me know

**Comment by Anjaliavv51** [comment]
@sejals23 sorry current Page looks good , please create some other issue.

**Pull request closed without merging**
