### PR TITLE
✨chatbot added✨

### PR DESCRIPTION
**Pull request by trahulprabhu38**
PR #443 has been resolved.
Screenshot 2024-10-13 at 1 38 08 PM

@Anjaliavv51 can you please review this.

### CODE REVIEW

**Comment by trahulprabhu38** [comment]
@Anjaliavv51 can you PR this once , else it will again create conflicts.
thank you

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 in menu.html page check in below image , cross check all remaining all html pages.


image

**Comment by trahulprabhu38** [comment]
ok it will be fixed in one min, kindly wait.

**Comment by T-Rahul-prabhu-38** [comment]
@Anjaliavv51 yup its fixed
for all pages.

**Comment by trahulprabhu38** [comment]
@Anjaliavv51 yup its fixed for all pages.

**Pull request merged**
