### PR TITLE
added retro art gallery in menu.html

### PR DESCRIPTION
**Pull request by SanikaBhalerao1345**
#190 can add retro style art gallery
in menu.html I have added an retro style art gallery section which has 4 types of paintings available.

## Related Issues

None
- Closes #

## Type of PR

- [feature request ] (can add retro style art gallery)

## Screenshots / videos (if applicable)

retro_after_changes

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@sanika1345 u had removed the transport div u add art gallery , instead u need top add separate one , please don't remove the code which is written
Thank You.

**Comment by SanikaBhalerao1345** [comment]
@Anjaliavv51 can u pls tell which transport div ..like from which section ..navbar??
sorry I'm new to open source..

**Comment by SanikaBhalerao1345** [comment]
@Anjaliavv51 can u pls check and merge my PR.
Thanks

**Comment by SanikaBhalerao1345** [comment]
hii @Anjaliavv51 pls add apt labels also

**Comment by Anjaliavv51** [comment]
> hii @Anjaliavv51 pls add apt labels also

please resolve the merge conflicts.

**Comment by SanikaBhalerao1345** [comment]
@Anjaliavv51 ok I will raise another PR ASAP but can u pls add gssoc and level label.
Thanks

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 ok I will raise another PR ASAP but can u pls add gssoc and level label. Thanks

No acrivity closed!

**Pull request closed without merging**
