### PR TITLE
Integrate Registration Pop up at home page

### LINKED ISSUE #522: ✨[feature Request]: Integrate Registration Pop up at home page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a Registration pop which provokes user to login for getting 30 % off for his first buy whenever someone tries to open website first time or not logged in they will get this pop up. I have also created UI design of this pop up, I am sending a pull request check it and hit me up for amy changes. Thank you. 

### Use Case

It will provoke users to sign in to our website.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by PrAyAg9**
## Description
This pull request introduces a new pop-up feature for user registration on the website. The pop-up aims to streamline the registration process, making it more accessible for users.

## Related Issues
 None

- Closes #522 

## Type of PR

- [X] (Feature Request)

## Screenshots / videos (if applicable)

IT's look :- 
image

## Checklist

- [X ] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X ] I have updated my branch and synced it with project `main` branch before making this PR
- [X ] I have performed a self-review of my code
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

You can close the pop by no thanks browse by full price OR click on logo on right of pop up -- it hides the pop up bar.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@PrAyAg9 ur feature is great but on clicking on signup now , Home screen is not accessible.

**Comment by Anjaliavv51** [comment]
https://github.com/user-attachments/assets/4a082a58-1b30-4c51-a539-fa9b14621651

no effect

**Comment by PrAyAg9** [comment]
@Anjaliavv51 Actually clicking on No thanks and retro logo will hide the pop up and it will only display if user is not logged in and  it's on landing page for first time.
AND about signup only thing it will do is to guide you to write a proper email, as i have to check if sign up has any backend for now i can make if email is right then pop will disapper and alert message will show discount has been sent to your email or if we can redirect to login/signup page. Whatever you say?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 Actually clicking on No thanks and retro logo will hide the pop up and it will only display if user is not logged in and it's on landing page for first time. AND about signup only thing it will do is to guide you to write a proper email, as i have to check if sign up has any backend for now i can make if email is right then pop will disapper and alert message will show discount has been sent to your email or if we can redirect to login/signup page. Whatever you say?

onclick to retro it need to redirect to login page , else after click on signup it need to redirect to index.html page.

**Comment by PrAyAg9** [comment]
@Anjaliavv51  I've made the changes as you have said :- 
Here's a video about it-


https://github.com/user-attachments/assets/136f0a94-5d15-4ad2-8618-9d4be834b066


Look at it.

**Comment by Anjaliavv51** [comment]
@PrAyAg9 yes thank for this feature Ready to merge

**Pull request merged**
