### PR TITLE
feat: add custom cursor for login, payment, and signup pages

### LINKED ISSUE #182: ✨[feature Request]: Replace Default Cursor with Custom Creative Cursor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We request a feature to replace the standard cursor with a unique, creative cursor design that enhances the website's aesthetic and user experience. A custom cursor can make the interface feel more interactive and engaging, aligning with the website's branding and theme.

### Use Case

- Enhanced Branding: Custom cursor aligns with the website's theme, reinforcing brand identity.
- Improved User Interaction: Makes interactions feel more refined and detailed.
- Increased Engagement: Creative animations and effects encourage exploration and content discovery.
- UI Differentiation: Helps users identify interactive elements and improves navigation.

### Benefits

- Improves the visual appeal and interactivity of the website.
- Aligns with the site's creative direction and enhances brand identity.

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by userAdityaa**
## Description

Custom cursors have been added to our login, payment, and sign-up pages. This update enhances user experience and reinforces our website identity.

## Related Issues

- Closes #182 

## Type of PR

- [x] (feature)

## Screenshots / videos (if applicable)

|Signup|Login|payment|
|----|----|----|
|Screenshot 2024-10-05 at 12 54 54 AM|Screenshot 2024-10-05 at 12 56 04 AM|Screenshot 2024-10-05 at 12 57 41 AM|

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by userAdityaa** [comment]
@Anjaliavv51, Ready for review!

**Comment by Anjaliavv51** [comment]
@userAdityaa I will merge the PR soon.

Changes are great but please remove existing cursor in signup and login.

**Comment by userAdityaa** [comment]
> @userAdityaa I will merge the PR soon.
> 
> Changes are great but please remove existing cursor in signup and login.

Hey @Anjaliavv51 , I didn't get what you mean by the eixisting one ?

**Comment by Anjaliavv51** [comment]
> > @userAdityaa I will merge the PR soon.
> > Changes are great but please remove existing cursor in signup and login.
> 
> Hey @Anjaliavv51 , I didn't get what you mean by the eixisting one ?

the cursor with circles.

**Comment by userAdityaa** [comment]
@Anjaliavv51, Ready for review!

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51, Ready for review!

resolve conflicts.

**Comment by userAdityaa** [comment]
> > @Anjaliavv51, Ready for review!
> 
> resolve conflicts.

Check it once.

**Pull request closed without merging**
