### PR TITLE
Add line on hover at footer

### PR DESCRIPTION
**Pull request by Shekhar-Raj**
## Description
Issue NO #507 

Successfully addded  the ine on hover, which will enhance the user interaction with website.

## Screenshots / videos (if applicable)

<h3>Before</h3>

https://github.com/user-attachments/assets/171581ea-f8d1-421a-b570-128cf68cbed6

<h2>After:</h2>

https://github.com/user-attachments/assets/4304d56d-4f10-4711-890b-7f545ece82ce

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
it should be like below.

https://github.com/user-attachments/assets/2494b737-538b-4b5c-996a-fccea6a34c31

**Comment by Shekhar-Raj** [comment]
> it should be like below.
> 
>  WhatsApp.Video.2024-10-14.at.21.15.24_8d3cb6a5.mp4

<h2>Done , Pls Review !</h2>

https://github.com/user-attachments/assets/8a07ac7d-54ab-48fe-8f2b-1076127be7ca

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj i will attach label level 3 if u implement these changes to all html files.

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj i will attach label level 3 if u implement these changes to all html files.

@Anjaliavv51  I will do it !

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj i will attach label level 3 if u implement these changes to all html files.

@Anjaliavv51  I Have successfully updated all the html files according to you .

<h2>Please assign the level 3 , as said by you, will be motivated to contribute further!</h2>

<h3>Demo:</h3>

<h4>cart.html</h4>


https://github.com/user-attachments/assets/762706f5-1d08-44c1-8d1f-5bffaa8db7ed

**Pull request merged**
