### PR TITLE
Change in HTML -index and menu file

### PR DESCRIPTION
**Pull request by sumitrajput96**
## Description
Changes in menu.html color are same as index file on footer div and social media icon color are different so i changes and same as index file into menu file. 

## Type of PR

- Enhancement

## Screenshots / videos (if applicable)

Screenshot 2024-10-02 180857
Screenshot 2024-10-02 180919
i changes in both html file in same heading color and social meadia icon color 

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@sumitrajput96 please mention the issue number and full the PR form properly

**Comment by Anjaliavv51** [comment]
@sumitrajput96 please also resolve conflicts

**Comment by sumitrajput96** [comment]
Ok Done,  Please merge

**Comment by Anjaliavv51** [comment]
@sumitrajput96 please fill the PR template and mention the issue number

**Comment by sumitrajput96** [comment]
Mam, I was direct changes without create issue in github but my changes was correct and good for project so i have no issue number

**Comment by sumitrajput96** [comment]
Mam, please merge the request

**Pull request merged**
