### PR TITLE
Added backend authendication using Mongo node and express

### PR DESCRIPTION
**Pull request by Abhishek-TG18**
# Pull Request Format
### Issue #314   : **Implement Authentication using MongoDB, Node.js, and Express.js [backend]** solved
#
## Type of PR
- **Add X in the box to specify the improvement type.**
- [] Bug fix
- [ x] Feature enhancement
- [ ] Documentation update
- [x ] BackendUpdate

## Description
This pull request includes the implementation of the backend functionality for user authentication and management. The following features have been added:

- 
- #Signup: Users can register with their email and password. The server validates the input and stores the user information in the database.
- #Sign-in: Registered users can log in by providing valid credentials.
- #User Details: Once logged in, users can retrieve their account information from the database.
- #Signout: Users can securely log out of their accounts.

All routes and logic have been implemented and tested with Postman. Please review and merge.

## Checklist
- **Add X in the box to specify.**
- [X] I have performed a self-review of my code.
- x[ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

### **Information to Start the server**
image
image

Feel free to ask  if you have any doubt

I have tested the code using Postman API Testing here are the demo videos

https://github.com/user-attachments/assets/c75322b0-5d83-4ef3-a0ae-f4503dba8463

https://github.com/user-attachments/assets/5ed926a1-cec8-4e9c-a51f-f261a32561d3

https://github.com/user-attachments/assets/f4ab790a-96e7-4170-ba99-3d0dc16c24e5

https://github.com/user-attachments/assets/7b222d0a-aaa9-4865-90aa-c9840385a194

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Abhishek-TG18 i need to implement those methods mentioned in video by u right?

**Comment by Anjaliavv51** [comment]
www.linkedin.com/in/lakshmi-pavananjali-pamidi-766760296

please ping me in linkedin

**Comment by Anjaliavv51** [comment]
@Abhishek-TG18 code scanning results shows failed y?

**Comment by Anjaliavv51** [comment]
@Abhishek-TG18 our repo is of files HTML CSS JS only

image


in the above pic , main is index.js

**Comment by Abhishek-TG18** [comment]
> @Abhishek-TG18 code scanning results shows failed y?

DON'T worry. That I  have console some information  related to sign in 
During connecting to front end I will remove those

**Comment by Abhishek-TG18** [comment]
Please once see LinkedIn

**Pull request merged**
