### PR TITLE
Add icons to login and signup pages

### LINKED ISSUE #420: ✨[feature Request]: Add icons on the login card
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Screenshot (1096)

image

The current login and signup pages card looks very plain and the ui seen unattractive.

### Use Case

I will add icons revelent to the site and make the ui of the site better.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Vaishh18**
## Description
Added images and icons to the signup and login cards

## Related Issues

- Closes  #420

## Type of PR

- [X] (Feature)

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/0e9bc11f-fd83-4e32-bf4a-6c7bc53dba08

Screenshot (1116)

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Vaishh18 the below image is not required please this with something.


image

**Comment by Vaishh18** [comment]
@Anjaliavv51 shall I add something reated to retoro theme or let it be as it is?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 shall I add something reated to retoro theme or let it be as it is?

yes

**Comment by Vaishh18** [comment]
@Anjaliavv51 Made changes 

Screenshot 2024-10-14 235315

**Comment by Vaishh18** [comment]
@Anjaliavv51 changes made

**Pull request merged**
