### PR TITLE
Updated Dark mode file

### PR DESCRIPTION
**Pull request by ChampGupta**
## Description
Dark Mode feature #542

## Related Issues

None

## Type of PR

- [ ] ()

## Checklist

- [X ] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ X] I have performed a self-review of my code
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ChampGupta** [comment]
I fix the issue faced in #542 check and tell if problem again occurs. Also merge if fine asap

**Comment by Anjaliavv51** [comment]
@ChampGupta resolve the conflicts

**Comment by ChampGupta** [comment]
@Anjaliavv51 conflicts resolved.

**Comment by ChampGupta** [comment]
@Anjaliavv51 Conflicts are resolved
Screenshot 2024-10-23 at 5 58 25 AM

**Comment by ChampGupta** [comment]
Please merge branch asap

**Pull request closed without merging**
