### PR TITLE
Making Contact Page Footer consistent with Home Page Footer

### PR DESCRIPTION
**Pull request by Orca-63**
Make the footer design on contact page same as the home page.
## Description
The footer design on the home page and the contact page  were differing, leading to an inconsistent user experience. I have designed the footer of the contact page similar to the home page for a better layout of the website.

## Related Issues

None
- Closes #

## Type of PR

- [X] (feature Request)

## Screenshots / videos (if applicable)
Before:
Contact Page : 
Screenshot 2024-10-02 201052
Home Page : 
Screenshot 2024-10-02 201245

After:
Contact Page : 
Screenshot 2024-10-02 215354
Home Page : 
Screenshot 2024-10-02 215424

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Orca-63 please resolve the conflicts.

**Comment by Orca-63** [comment]
@Anjaliavv51 I have resolved the conflicts now

**Comment by Anjaliavv51** [comment]
@Orca-63 do contribute to our repo frequently.

**Comment by Orca-63** [comment]
@Anjaliavv51 Yes sure , I really enjoyed contributing to this repository !

**Pull request merged**
