### PR TITLE
format the contact us page better #13

### PR DESCRIPTION
**Pull request by Shekhar-Raj**
<h2>I tried to make some changes , it was difficult to change the whole page format, so I changed the form, and made it look better than before, I would highly appreciate if you at least merge this request to make me motivated, and I can contribute more in future!, Thank you </h2>

<h3>Before:</h3>

image

<h3>After:</h3>

https://github.com/user-attachments/assets/bef50f43-9b08-4f5a-87c6-38d91bfe66c0

### CODE REVIEW

**Comment by Shekhar-Raj** [comment]
I need your little bit help it is showing some conflicts can u help me , how to resolve?

**Comment by Anjaliavv51** [comment]
> I need your little bit help it is showing some conflicts can u help me , how to resolve?

Yes sure.

**Comment by Shekhar-Raj** [comment]
can u pls review and merge so that i can proceed further and get by labels!

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj please change the changes of button to normal u had changed the color of subscribe button too , once please check.

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj please change the changes of button to normal u had changed the color of subscribe button too , once please check.

@Anjaliavv51 <h3>Changed the changes of button to normal,  and for  subscribe button, can u please tell me specifically which subscribe button?</h3>

**Comment by Anjaliavv51** [comment]
> > @Shekhar-Raj please change the changes of button to normal u had changed the color of subscribe button too , once please check.
> 
> @Anjaliavv51
> 
> ### Changed the changes of button to normal, and for subscribe button, can u please tell me specifically which subscribe button?

Subscribe button located in footer section.

**Comment by Shekhar-Raj** [comment]
> > > @Shekhar-Raj please change the changes of button to normal u had changed the color of subscribe button too , once please check.
> > 
> > 
> > @Anjaliavv51
> > ### Changed the changes of button to normal, and for subscribe button, can u please tell me specifically which subscribe button?
> 
> Subscribe button located in footer section.

<h3>I am unable to find? are you talking about Those Social Icons? </h3>

**Comment by Anjaliavv51** [comment]
> > > > @Shekhar-Raj please change the changes of button to normal u had changed the color of subscribe button too , once please check.
> > > 
> > > 
> > > @Anjaliavv51
> > > ### Changed the changes of button to normal, and for subscribe button, can u please tell me specifically which subscribe button?
> > 
> > 
> > Subscribe button located in footer section.
> 
> ### I am unable to find? are you talking about Those Social Icons?

No wait

**Comment by Anjaliavv51** [comment]
Screenshot_20241003_131744_Chrome
Screenshot_20241003_131739_Chrome
These two

**Comment by Shekhar-Raj** [comment]
> > > > > @Shekhar-Raj please change the changes of button to normal u had changed the color of subscribe button too , once please check.
> > > > 
> > > > 
> > > > @Anjaliavv51
> > > > ### Changed the changes of button to normal, and for subscribe button, can u please tell me specifically which subscribe button?
> > > 
> > > 
> > > Subscribe button located in footer section.
> > 
> > 
> > ### I am unable to find? are you talking about Those Social Icons?
> 
> No wait

<h3>Can u pls check now</h3>
<h4>Issue No </h4>
#13

**Comment by Shekhar-Raj** [comment]
<h2>Button Changes</h2>


https://github.com/user-attachments/assets/3d5bda64-92c4-4d74-bd87-d748c5c0291f

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj it should have hover background color

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj it should have hover background color

on both  buttons? and which background color?

**Comment by Shekhar-Raj** [comment]
<h2>Is this fine ?</h2> @Anjaliavv51 


https://github.com/user-attachments/assets/8a01ef47-985a-4330-ac0b-864d1f534bed

**Comment by Anjaliavv51** [comment]
@Shekhar-Raj Thankyou for contributing very patiently!

**Pull request merged**
