### PR TITLE
✨Add Visitor Counter feature done ! #694

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #694
Add Visitor Counter feature done properly -

Screenshot 2024-10-23 190814

Before -

Screenshot 2024-10-23 190827

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 merge my PR with level 3, If you check other projects, they are also giving level 3 for this... you can check my code also..

Screenshot 2024-10-22 204511


Thank you 🙏🏻

**Comment by Subhajit-2023-44** [comment]
> @Anjaliavv51 merge my PR with level 3, If you check other projects, they are also giving level 3 for this... you can check my code also..
> 
> Screenshot 2024-10-22 204511
> 
> Thank you 🙏🏻

@Anjaliavv51

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 today is the last day please merge my PR with level 3 ..

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51  ??

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 ??

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Subhajit-2023-44  cannot see ur visitors button in deployment


image

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 cannot see ur visitors button in deployment
> 
> image

@Anjaliavv51 PA but, I did everything right, it shows up correctly on my device -


https://github.com/user-attachments/assets/2cd659de-6da8-4b9e-948e-09b60fa6cb71


I also did this in other websites... please check and merge my PR

Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@Anjaliavv51 please check and merge my PR, otherwise i can't able to do another task...

**Comment by Anjaliavv51** [comment]
@Subhajit-2023-44 still unable to see the visitors count.

image

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 still unable to see the visitors count.

@Anjaliavv51 okay, can you please check it in another browser..

**Comment by Subhajit-2023-44** [comment]
I will give a new PR soon, wait

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 still unable to see the visitors count.
> 


@Anjaliavv51 I hope the issue is resolved now #810, Please check & merge my PR 

Thank You

**Pull request closed without merging**
