### PR TITLE
[Feature Request]: Add a forgot password page

### LINKED ISSUE #375: ✨[feature Request]: Add a forgot password page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently there is only signup and login page but no forgot passsword page i want to work on that 

### Use Case

It will help users to reset password

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by amitroy-thedev**
## Description
Added a forgot password page

## Related Issues

- Closes #375 

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)
Screenshot 2024-10-09 153508

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@amitroy-thedev add forget pass link above , 
Don’t have an account?

**Comment by amitroy-thedev** [comment]
image
i have added the forgot password link in login page

**Comment by amitroy-thedev** [comment]
would you make request for changes so that i can make changes here

**Comment by Anjaliavv51** [comment]
> would you make request for changes so that i can make changes here

?

**Pull request closed without merging**
