### PR TITLE
The UI of the contactUs page has been updated 

### PR DESCRIPTION
**Pull request by trahulprabhu38**
## Related Issues

Fixed the UI

## Type of PR

- [X] (enhancement)

## Screenshots / videos (if applicable)
Screenshot 2024-10-02 at 2 53 21 PM

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anjaliavv51/Retro)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by trahulprabhu38** [comment]
i have created a PR , so what is the procedure after this?

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 u need to change even for other html pages.

**Comment by trahulprabhu38** [comment]
the change is reflecting on footers of all the pages.

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 it is not applied to index.html page

**Comment by trahulprabhu38** [comment]
oh im sorry for the trouble , ill hotfix it right now.

**Comment by Anjaliavv51** [comment]
@T-Rahul-prabhu-38 y u closed the issue.

**Pull request closed without merging**
